# Generated by Django 4.0.4 on 2022-05-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_groupmember_task_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed']},
        ),
        migrations.AddField(
            model_name='group',
            name='groupname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
