# Generated by Django 4.0.4 on 2022-06-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_quantity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('groupcode',), name='uniquegroupname'),
        ),
    ]
