# Generated by Django 4.0.4 on 2022-06-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_group_uniquegroupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupname',
            field=models.CharField(default='C2B115', max_length=200, unique=True),
        ),
    ]
