# Generated by Django 4.0.4 on 2022-06-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_group_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupcode',
            field=models.CharField(default='B12AEE', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupname',
            field=models.CharField(max_length=200),
        ),
    ]
